### ISSUE TITLE
Fix CSP

### ISSUE THREAD

**Issue by jackmerrill** [astralservices/docs#5]
Could use some help from @doamatto on this;

Lighthouse reports a bunch of CSP errors and such and I have no idea how to fix it.

**Comment by doamatto** [comment]
Link to report ?

**Comment by jackmerrill** [comment]
https://googlechrome.github.io/lighthouse/viewer/?gist=505feaca4fc1617957ebd636c2fdc899

**Comment by doamatto** [comment]
Move all inline scripts to actual files and harden CSP. That should solve the first three in the table. Default src doesn't apply to images, so you'll have to explicitly define that to fix the last two.

**Comment by jackmerrill** [comment]
They are all in actual files (/js/foobar.js) locally, so I have no idea what to do here. I'm pretty bad with CSP as well lol

**Comment by doamatto** [comment]
Some for inlines; this time in the <head>
![image](https://user-images.githubusercontent.com/30969346/164752069-d6ce9d81-a121-4704-9dd5-021417e0d9b3.png)

**Comment by jackmerrill** [comment]
So that first inline is Cloudflare, not sure if I can do anything about that.

I'll take a look at the second and third ones.
